USE [master]
GO

CREATE DATABASE [Workout]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Workout', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Workout.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Workout_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Workout_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Workout] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Workout].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Workout] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Workout] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Workout] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Workout] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Workout] SET ARITHABORT OFF 
GO

ALTER DATABASE [Workout] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Workout] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Workout] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Workout] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Workout] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Workout] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Workout] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Workout] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Workout] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Workout] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Workout] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Workout] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Workout] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Workout] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Workout] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Workout] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Workout] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Workout] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Workout] SET  MULTI_USER 
GO

ALTER DATABASE [Workout] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Workout] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Workout] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Workout] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Workout] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Workout] SET  READ_WRITE 
GO

USE [Workout]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Exercise](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Description] [varchar](200) NULL,
 CONSTRAINT [PK_Exercise] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [Workout]
GO

/****** Object:  INSERT SOME DATA ******/
INSERT INTO [dbo].[Exercise]
           ([Name]
           ,[Description])
     VALUES
           ('Clean'
           ,'Clean exercise description');

INSERT INTO [dbo].[Exercise]
           ([Name]
           ,[Description])
     VALUES
           ('Jerk'
           ,'Jerk exercise description');


INSERT INTO [dbo].[Exercise]
           ([Name]
           ,[Description])
     VALUES
           ('Clean and Jerk'
           ,'Clean and Jerk exercise description');
GO



